spring:
  application:
    name: batch-processor
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://admin:AdminPassword123@deliverynow-cluster.gg846.mongodb.net/?retryWrites=true&w=majority&appName=deliverynow-cluster}
      database: deliverynow-db
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:key}
        secret-key: ${AWS_SECRET_ACCESS_KEY:key}
        session-token: ${AWS_SESSION_TOKEN:session}
server:
  port: 5001

resources:
  temp:
    video: src/main/resources/temp
    images: src/main/resources/images
    zip: src/main/resources/arquivo

aws:
  sqs:
    email:
      name: filezip-process-queue
      url: https://sqs.us-east-1.amazonaws.com/110832778598/filezip-send_email_queue

