apiVersion: v1
kind: Service
metadata:
  name: svc-filezip-processor-order
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 31001
      targetPort: 8081
  selector:
    app: service--filezip-processor